# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./dist:/app/dist
#     command: node main.js

#   nginx:
#     image: nginx:alpine
#     depends_on:
#       - app
#     ports:
#       - "80:80"
#     volumes:
#       - ./dist:/usr/share/nginx/html
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf


###


version: '3.8'

services:
  app:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app  # Mount current directory into the container
    command: sh -c "node main.js"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html  # Mount local dist directory to serve files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf